### ISSUE TITLE
Broken on 3.0.0-preview6

### ISSUE THREAD

**Issue by faberto** [BlazorExtensions/SignalR#32] opened 2019-06-13 21:12 UTC
Nuget Packet is Broken on 3.0.0-preview6. 
Sample is broken as well.

``2>Fatal error in IL Linker
2>
2>Unhandled Exception: Mono.Linker.MarkException: Error processing method: 'System.Threading.Tasks.Task Blazor.Extensions.HubConnection/<>c__DisplayClass30_0`10::<On>b__0(System.String[])' in assembly: 'Blazor.Extensions.SignalR.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve !!0 Microsoft.JSInterop.Json::Deserialize(System.String)
2>   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
2>   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
2>   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
2>   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
2>   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
2>   at Mono.Linker.Steps.MarkStep.ProcessQueue()
2>   --- End of inner exception stack trace ---
2>   at Mono.Linker.Steps.MarkStep.ProcessQueue()
2>   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
2>   at Mono.Linker.Steps.MarkStep.Process()
2>   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
2>   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
2>   at Mono.Linker.Pipeline.Process(LinkContext context)
2>   at Mono.Linker.Driver.Run(ILogger customLogger)
2>   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
2>   at Mono.Linker.Driver.Main(String[] args)``

**Comment by faberto** [comment] 2019-06-13 22:42
Cause and how to resolve: https://github.com/aspnet/Announcements/issues/364

**Comment by galvesribeiro** [comment] 2019-06-13 22:47
Thanks @faberto 

I'll implement it Tomorrow or over the weekend. Will keep this issue open to track the progress.

Thanks!

**Comment by endeffects** [comment] 2019-06-25 18:16
Please provide an update :(

**Comment by galvesribeiro** [comment] 2019-06-25 18:17
Sorry, will try to get to it until tomorrow. There are tons of PRs updating to Preview 6 on the other components as well. Hold tight!

**Comment by galvesribeiro** [comment] 2019-08-01 23:01
Hello folks, sorry for the delay. I guess the problem is gone and the preview7 package is out.

I'm closing the issue but feel free to re-open and ping me in case you still have issues on preview7.

Thanks!

**Closed by galvesribeiro** 2019-08-01 23:01 UTC
Labels: enhancement, good first issue
