### ISSUE TITLE
Upgrading Blazor WebAssembly to 3.1.0-preview4.19579.2 leads to an error: Could not find 'BlazorExtensions' in 'window'.

### ISSUE THREAD

**Issue by szmalec** [BlazorExtensions/SignalR#66] opened 2019-12-12 11:54 UTC
Recently I tried to update my blazor wasm project (which uses `Blazor.Extensions.SignalR v1.1.0-preview3`) to latest `3.1.0-preview4.19579.2` Blazor version.
After updating, an error began to appear in browser console:
```
Could not find 'BlazorExtensions' in 'window'. Error: Could not find 'BlazorExtensions' in 'window'.
 at http://localhost:7258/_framework/blazor.webassembly.js:1:8937
 at Array.forEach (<anonymous>)
 at p (http://localhost:7258/_framework/blazor.webassembly.js:1:8898)
 at Object.invokeJSFromDotNet (http://localhost:7258/_framework/blazor.webassembly.js:1:9470)
 at _mono_wasm_invoke_js_marshalled (http://localhost:7258/_framework/wasm/mono.js:1:165750)
 at wasm-function[6221]:0x11936a
 at wasm-function[1431]:0x402ee
 at wasm-function[636]:0x147cf
 at wasm-function[636]:0x19ae2
 at wasm-function[4996]:0xeb135
```

It is probably due to latest changes related to static assets in libraries - as we can see at https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-1/
```
Support for static assets in libraries when publishing
Standalone Blazor WebAssembly apps now support static assets from Razor class libraries both during development and when publishing. This applies to both standalone Blazor WebAssembly apps and ASP.NET Core hosted apps. Static assets are consumed from referenced libraries using the path prefix: _content/{LIBRARY NAME}/.
```
There is also PR @ AspNetCore src repo: https://github.com/aspnet/AspNetCore/pull/17353/files
Problem is also reported in several other projects which uses *.js static assets.

Initially I have also tried to update `Blazor.Extensions.SignalR` to `3.1.0-preview4.19579.2` and the same `Could not find 'BlazorExtensions' in 'window'` occured when `Blazor.Extensions.SignalR.Test.Server` started.

I have discovered some differences between old build output and new build output, eg.:

[old - netstandard2.0]
* there WAS: `test\Blazor.Extensions.SignalR.Test.Client\bin\Debug\netstandard2.0\dist\_content\Blazor.Extensions.SignalR.JS`
* there WAS: `"jsReferences": [ "_content/Blazor.Extensions.SignalR.JS" ]` entry in `test\Blazor.Extensions.SignalR.Test.Client\bin\Debug\netstandard2.0\dist\_framework\blazor.boot.json`

[new - netstandard2.1]
* `test\Blazor.Extensions.SignalR.Test.Client\bin\Debug\netstandard2.1\dist\_content\Blazor.Extensions.SignalR.JS` does NOT exists
* `test\Blazor.Extensions.SignalR.Test.Client\bin\Debug\netstandard2.1\dist\_framework\blazor.boot.js`on does NOT contain `"jsReferences": [ "_content/Blazor.Extensions.SignalR.JS" ]` entry

I have forked `Blazor.Extensions.SignalR` repo and I will try to prepare workaround...

**Comment by szmalec** [comment] 2019-12-12 14:02
In https://github.com/szmalec/SignalR/commit/ad290156caa14b7fa2aafc093daa201c8918c858 you can see modified `Blazor.Extensions.SignalR` version which works OK after update to `3.1.0-preview4.19579.2`.
As you probably discover there are some drawbacks:
- `blazor.extensions.signalr.js` file is NOT automatically loaded in client application - [new script entry entry had to be manually/explicitly added in wasm project](https://github.com/szmalec/SignalR/commit/ad290156caa14b7fa2aafc093daa201c8918c858#diff-510fe29504ea76af5434eeab2857593fR10) in `test\Blazor.Extensions.SignalR.Test.Client\wwwroot\index.html`: `<script src="_content/Blazor.Extensions.SignalR.JS/blazor.extensions.signalr.js"></script>`
- `app.UseStaticFiles();` [had to be added to](https://github.com/szmalec/SignalR/commit/ad290156caa14b7fa2aafc093daa201c8918c858#diff-ac87224757aab2e808734dd5df9e8afeR111) `test\Blazor.Extensions.SignalR.Test.Server\Startup.cs`

It looks that previously existed entry `<EmbeddedResource Include="wwwroot\**\*.js" LogicalName="blazor:js:%(RecursiveDir)%(Filename)%(Extension)" />` in `Blazor.Extensions.SignalR.JS.csproj` is not taken into account (is not used)?

Am I wrong at any of above points?

---

So if anyone wants to have 3.1.0-preview4.19579.2 and Blazor.Extensions.SignalR then can use my temporary solution.
Otherwise maybe it would be better to wait, because there are some currently unresolved issues which have "asset" in title, eg. for [blazor-wasm-3.2-preview1](https://github.com/aspnet/AspNetCore/milestone/79)...

**Comment by AlexanderJohnston** [comment] 2019-12-23 21:12
I cannot find the `Blazor.Extensions.SignalR.JS` file to put into my `_content` folder. Where are you guys getting that?

This issue is blocking my team from doing any work right now. Do we have any fixes? I tried following what you guys are talking about up above but I cannot reproduce your fix.

**Comment by TroelsL** [comment] 2019-12-27 21:31
Ran into the same issue, even managed to replace the BlazorExtensions.Storage with another solution before finding out what the root issue was.

I'd very much also appreciate a bit more elaborate (or dumbed down, if you will) set of workaround steps if anyone is able and willing. I haven't been able to locate another solution for doing SignalR in Blazor WASM.

**Comment by coj337** [comment] 2019-12-29 01:51
It's just a temporary fix until the proper patch is merged in but you can compile the js manually and reference that from your index.html
(Here's mine if you're lazy, just change the extension to js [blazor.extensions.signalr.txt](https://github.com/BlazorExtensions/SignalR/files/4007658/blazor.extensions.signalr.txt))

**Comment by cmoski** [comment] 2020-01-07 01:15
Ran into this issue while attempting to develop a test application -- would very much appreciate a newbie friendly fix.

**Comment by cmoski** [comment] 2020-01-07 01:34
I was able to get around this issue by creating a new Razor Class Library, and adding: https://github.com/BlazorExtensions/SignalR/files/4007658/blazor.extensions.signalr.txt (renamed to .js) to RazorClasssLibrary\wwwroot\Blazor.Extensions.SingalR.js and adding the following:

`<script type="text/javascript" src="_content/RazorClasssLibrary/Blazor.Extensions.SignalR.js"></script>` to index.html

Once I did this, it appears the websocket was at least connecting. (Although I don't have more information on if there is a better place to put this reference.)

**Comment by PierpaoloBattaglioneSpecifi** [comment] 2020-01-16 14:30
Actually with all the changes made in @szmalec's branch everything works, even in WebAssembly. Is this project still maintained? Can we open a PR? Are we waiting for [blazor-wasm-3.2-preview1
](https://github.com/dotnet/aspnetcore/milestone/79)?

**Comment by EugeneScully** [comment] 2020-01-21 23:00
> Are we waiting for [blazor-wasm-3.2-preview1](https://github.com/dotnet/aspnetcore/milestone/79) to be released?

It looks like a SignalR client is scheduled for 3.2-preview3:
https://github.com/dotnet/aspnetcore/milestone/81
https://github.com/dotnet/aspnetcore/issues/13503

**Comment by szmalec** [comment] 2020-01-29 11:23
It looks that we can now forget about problems with Blazor Extensions SignalR and use Microsoft.AspNetCore.SignalR.Client directly - see "Support for the .NET SignalR client" section @ https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-1-release-now-available/

**Comment by galvesribeiro** [comment] 2020-01-29 11:29
@szmalec Yes, the SignalR client is now supported on WebAssembly as expected.

One quick note... Before you blame _"Blazor Extensions SignalR problems"_, please read the real reason why it has _problems_ before start attacking others. 

For future readers, the problem is caused because Blazor changed the way it deals with static content (CSS/JS) and that breaks every single extension out there making components useless. 

As [stated here](https://github.com/BlazorExtensions/Home/issues/14) we are working on bring a solution for this issue that doesn't requires manual interaction with JS/CSS files by the final user otherwise, it will not make any sense at all. It beats the purpose of a NuGet package in its essence.

**Closed by galvesribeiro** 2020-01-29 11:29 UTC

**Comment by szmalec** [comment] 2020-01-29 21:44
@galvesribeiro 
I didn't want it to sound like that. I know that SignalR Blazor Extensions should not be blamed for problems resulting from changes in the WASM Blazor - **which is still in preview phase**. 
I just hoped that using the official SignalR client could be a better idea to bypass the likely temporary issues reported in [this issue](https://github.com/BlazorExtensions/SignalR/issues/66).

I know that SignalR Blazor Extensions is a piece of awesome work - thank you for your commitment and willingness to share the results of your hard work with the community!!

Now I also know that the recommendation of switching to the official Microsoft.AspNetCore.SignalR.Client in the WASM Blazor apps was not necessarily a good move (at least for now when blazor wasm is not officialy production ready), because after migration I encountered other [problems (related to JWT auth)](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-1-release-now-available/#comment-1336) ~~which I mention [here](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-1-release-now-available/#comment-1329) (comment still not moderated - so not publicly available)~~  ;)

So again - we should remember that Blazor WASM is still an alpha phase;)
